#!/bin/bash

case "${1:-}" in
r)
  operator-sdk run --local
  ;;
g)
  operator-sdk generate crds
  operator-sdk generate k8s
  ;;
da)
  kubectl delete -f deploy/crds/hypercloud.tmaxanc.com_v1alpha1_virtualmachineimage_cr.yaml --ignore-not-found=true
  kubectl delete -f deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml --ignore-not-found=true
  ;;
dcr)
  kubectl delete -f deploy/crds/hypercloud.tmaxanc.com_v1alpha1_virtualmachineimage_cr.yaml --ignore-not-found=true
  ;;
dcrd)
  kubectl delete -f deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml --ignore-not-found=true
  ;;
do)
  ;;
aa)
  kubectl apply -f deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
  kubectl apply -f deploy/crds/hypercloud.tmaxanc.com_v1alpha1_virtualmachineimage_cr.yaml
  ;;
acr)
  kubectl apply -f deploy/crds/hypercloud.tmaxanc.com_v1alpha1_virtualmachineimage_cr.yaml
  ;;
acrd)
  kubectl apply -f deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
  ;;
*)
    echo " $0 [command]
Development Tools Box

Available Commands:
  r     Run local controller
  g     Generate code
  da    Delete All
  dcr   Delete CR
  dcrd  Delete CRD
  do    Delete all object created by crd
  aa    Apply All
  acr   Apply CR
  acrd  Apply CRD
" >&2
    ;;
esac

