#!/bin/bash

function lint() {
  golangci-lint run ./... -v
}

function unit() {
  operator-sdk test local ./pkg/... --debug --verbose
}

# TODO: better...
function codegen() {
  operator-sdk generate crds
  operator-sdk generate k8s
  git status --porcelain 2>/dev/null| grep "^??" | wc -l
}

function e2e() {
  operator-sdk test local ./e2e --debug --verbose --image quay.io/tmaxanc/kubevirt-image-service:canary
}

function build() {
  docker rmi quay.io/tmaxanc/kubevirt-image-service:canary
  operator-sdk build quay.io/tmaxanc/kubevirt-image-service:canary
  docker login -u="tmaxanc+robot" -p="63GPHMM2K3FB7UARJBYIZPMKGAGQ2UWZ4FZZI6HYP6NX6T94IWH99YKIGI37INIU" quay.io
  docker push quay.io/tmaxanc/kubevirt-image-service:canary
}

function minikube() {
  sudo minikube delete
  sudo rm -rf /var/lib/rook
  CHANGE_MINIKUBE_NONE_USER=true sudo -E minikube start --driver=none --kubernetes-version=v1.17.3
  kubectl apply -f ./hack/rook-ceph/common.yaml
  kubectl apply -f ./hack/rook-ceph/operator.yaml
  kubectl wait --for=condition=Available deployment/rook-ceph-operator -n rook-ceph
  kubectl apply -f ./hack/rook-ceph/cluster-test.yaml
  wait_condition "kubectl get cephclusters.ceph.rook.io -n rook-ceph | grep Created" 300
  kubectl apply -f ./hack/rook-ceph/storageclass-test.yaml
  kubectl apply -f ./hack/rook-ceph/snapshotclass.yaml
  sleep 5
}

function minikube_clean() {
  sudo minikube delete
  sudo rm -rf /var/lib/rook
}

function wait_condition {
  cond=$1
  timeout=$2

  for ((i=0; i<timeout; i+=5)) do
    echo "Waiting for ${i}s condition: \"$cond\""
    if eval $cond > /dev/null 2>&1; then echo "Conditon met"; return 0; fi;
    sleep 5
  done

  echo "Condition timeout"
  return 1
}

case "${1:-}" in
lint)       lint;;
unit)       unit;;
codegen)    codegen;;
build)      build;;
minikube)   minikube;;
minikube_clean) minikube_clean;;
e2e)        e2e;;
*)
    echo " $0 [command]
Test Toolbox

Available Commands:
  lint
  unit
  codegen
  build
  minikube
  minikube_clean
  e2e
" >&2
    ;;
esac

