#!/bin/bash

function lint() {
  golangci-lint run ./... -v
}

function unit() {
  operator-sdk test local ./pkg/... --debug --verbose
}

# TODO: better...
function codegen() {
  operator-sdk generate crds
  operator-sdk generate k8s
  git status --porcelain 2>/dev/null| grep "^??" | wc -l
}

function e2e() {
  operator-sdk test local ./e2e --debug --verbose
}

case "${1:-}" in
lint)       lint;;
unit)       unit;;
codegen)    codegen;;
e2e)        e2e;;
build)
  operator-sdk build quay.io/woohhan/kubevirt-image-service:canary
  ;;
minikube)
  # TODO: deploy rook
  sudo minikube delete
  CHANGE_MINIKUBE_NONE_USER=true sudo -E minikube start --driver=none --kubernetes-version=v1.17.3
  ;;
minikube_clean)
  sudo minikube delete
  ;;
deploy)
  kubectl apply -f deploy/role.yaml
  kubectl apply -f deploy/role_binding.yaml
  kubectl apply -f deploy/service_account.yaml
  kubectl apply -f deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
  sed 's|kubevirt-image-service:latest|kubevirt-image-service:canary|' deploy/operator.yaml | kubectl apply -f -
  ;;
*)
    echo " $0 [command]
Test Toolbox

Available Commands:
  lint
  unit
  codegen
  build
  minikube
  minikube_clean
  deploy
  e2e
" >&2
    ;;
esac

