name: kubevirt-image-service
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  unit_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: unit test
        run: ./testbox unit
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
  codegen_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: codegen test
        run: ./testbox codgen
  e2e_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - uses: actions/checkout@v2
      - name: minikube start
        run: |
          ./testbox minikube download
          ./testbox minikube start
          ./testbox rook_install
      - name: build
        run: |
          ./testbox operator-sdk_install
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          ./testbox build
      - name: e2e test
        run: ./testbox e2e
  deploy-latest:
    if: github.ref == 'refs/heads/master'
    needs: [unit_test, lint, codegen_test, e2e_test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ./testbox operator-sdk_install
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          ./testbox build
      - name: push
        run: |
          docker tag quay.io/tmaxanc/kubevirt-image-service:canary quay.io/tmaxanc/kubevirt-image-service:latest
          docker push quay.io/tmaxanc/kubevirt-image-service:latest
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [unit_test, lint, codegen_test, e2e_test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ./testbox operator-sdk_install
          docker login -u=tmaxanc+robot -p=${{ secrets.QUAY_PASSWORD }} quay.io
          ./testbox build
      - name: push
        run: |
          docker tag quay.io/tmaxanc/kubevirt-image-service:canary quay.io/tmaxanc/kubevirt-image-service:${GITHUB_REF#refs/tags/}
          docker push quay.io/tmaxanc/kubevirt-image-service:${GITHUB_REF#refs/tags/}
